### ISSUE TITLE
Install Errors

### ISSUE THREAD

**Issue by cspaniard** [TimLuq/node-elgato-stream-deck#2]
Hello,

when I try to install I get the following error

```
$ npm install --save stream-deck-ts
npm ERR! Unexpected end of JSON input while parsing near '...Y1AP/2aqfdbysmO3zAZuc'
```

any ideas ? How could I fix it ?

TIA,
David

**Comment by TimLuq** [comment]
Hello David,

Unfortunately I doubt this has anything to do with this package specifically. Either your environment is corrupt or there's something wrong in a dependency. If you run npm in verbose mode you may get more information regarding the problem.
